os: linux
dist:
    - bionic # PAPI 5.6.0
    - eoan   # PAPI 5.7.0
arch:
    - amd64
    - ppc64le
    - arm64

language: rust
rust:
    - stable

cache: cargo
before_cache:
    # Travis can't cache files that are not readable by "others"
    - chmod -R a+r $HOME/.cargo

addons:
    apt:
        packages:
            - libpapi-dev
            - libpapi5

script:
    - cargo build --verbose --all
    - cargo test --verbose --all

notifications:
    email:
        on_success: never
