[package]
name = "papi-sys"
version = "0.3.0"
authors = ["Clemens Lutz <lutzcle@cml.li>", "Yeonsoo Kim <alkorang@outlook.com>"]
license = "MIT OR Apache-2.0"
build = "build.rs"
links = "papi_wrapper"

[dependencies]

[build-dependencies]
bindgen = "0.50"
